tagFormat: "${version}"
branches:
  - main
  - { name: beta, prerelease: true }
  - { name: rc, prerelease: true }

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - { breaking: true, release: major }
        - { revert: true, release: patch }
        - { type: feat, release: minor }
        - { type: ci, release: patch }
        - { type: doc, release: patch }
        - { type: docs, release: patch }
        - { type: fix, release: patch }
        - { type: perf, release: patch }
        - { type: refactor, release: patch }
        - { type: test, release: patch }
        - { type: tests, release: patch }
        - { type: chore, release: false }
        - { scope: no-release, release: false }
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - { type: feat, section: "Features" }
          - { type: new, section: "Features" }
          - { type: fix, section: "Bug Fixes" }
          - { type: doc, section: "Documentation" }
          - { type: docs, section: "Documentation" }
          - { type: chore, section: "Misc" }
          - { type: perf, section: "Misc" }
          - { type: refactor, section: "Misc" }
          - { type: ci, section: "Automation" }
          - { type: test, section: "Automation" }
          - { type: tests, section: "Automation" }
  - "@semantic-release/changelog"
  - "@semantic-release/gitlab"
  - "semantic-release-pypi"
  - - "@semantic-release/git"
    - assets: [ CHANGELOG.md, pyproject.toml ]
      message: "chore(release): Release ${nextRelease.version} update changelog [skip ci]\n\n${nextRelease.notes}"
